version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: users_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - spring_db:/var/lib/mysql
volumes:
  spring_db: